install.packages("installr")
library(installr)
updateR()

install.packages('extrafont')
library(extrafont)
font_import()
loadfonts()

source("https://bioconductor.org/biocLite.R")
biocLite("SNPRelate")
biocLite("ConsensusClusterPlus")

install.packages("ape")
install.packages("plyr")
install.packages("dplyr")
install.packages("adegenet")
install.packages("poppr")
install.packages("dbscan")
install.packages("scrime")
install.packages("circlize")
install.packages("dendextend")
install.packages("stringr")